---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/homeownership-tsa")
```
```{r}
library(mgcv)
library(lubridate)
library(dplyr)
library(xts)
library(ggplot2)
library(ggpubr)
library(corrplot)
library(fpp2)
```
```{r}
hosr_var_fpath <- "~/Documents/GitHub/homeownership-tsa/data/hosr_var.csv"

hosr_var_df <- read.csv(hosr_var_fpath)
```

```{r}
points <- 1:length(hosr_var_df$date)
points <- (points - min(points))/max(points)

hosr_ts <- ts(hosr_var_df$hosr,start = 1980, frequency = 12)

# 1. Fit a moving average model
mav_model <- ksmooth(points, hosr_var_df$hosr, kernel = "box")
mav_fit <- ts(mav_model$y, start = 1980, frequency = 12)

# 2. Fit mean model
mean_model <- meanf(hosr_ts)
mean_fit <- ts(mean_model$fitted, start = 1980, frequency = 12)

# 3. Fit drift model
drift_model <- rwf(hosr_ts,12,drift=TRUE)
drift_fit <- ts(drift_model$fitted, start = 1980, frequency = 12)

# 4. Fit naive model
naive_model <- naive(hosr_ts,12)
naive_fit <- ts(naive_model$fitted, start = 1980, frequency = 12)

# plot
ts.plot(hosr_ts,xlab="",ylab="homeownership rate",main = "Trend Estimation with Benchmark model")
lines(mav_fit,lwd=2,col="blue")
lines(mean_fit,lwd=2,col="red")
lines(drift_fit,lwd=2,col="green")
lines(naive_fit,lwd=2,col="yellow")

legend("topleft", legend = c("mav", "mean", "drift", "naive"),
col = c("blue", "red", "green", "yellow"), lwd = 2)
```
```{r}
mav_diff <- hosr_ts - mav_fit
mean_diff <- hosr_ts - mean_fit
drift_diff <- hosr_ts - drift_fit
naive_diff <- hosr_ts - naive_fit

par(mfrow = c(2,2))
acf(mav_diff)
acf(mean_diff)
acf(drift_diff[2:length(drift_diff)])
acf(naive_diff[2:length(naive_diff)])

```

There are still non linear trend in the residuals of moving average model and mean model. However,drift and naive exhibit to remove the trend in the time series data.
